artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/refs/heads/main/Maternal%20Health%20Risk%20Data%20Set.zip
  loacl_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir : artifacts/data_validation
  unzip_dir: artifacts\data_ingestion\Maternal Health Risk Data Set.xls
  Status_file: artifacts/data_validation/Status.txt

data_transfomation:
  root_dir: artifacts/data_transfomation
  data_path: artifacts\data_ingestion\Maternal Health Risk Data Set.xls
  Status_file: artifacts/data_validation/Status.txt

model_train:
  root_dir: artifacts/model_train
  train_data_path: artifacts\data_transfomation\train.csv
  test_data_path: artifacts\data_transfomation\test.csv
  model_file: model.joblib
  preprocess_file: preprocess.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_file: artifacts\model_train\model.joblib
  preprocess_file: artifacts\model_train\preprocess.joblib
  metrics_file: artifacts/model_evaluation/metrics.json


  

