artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://github.com/ldotmithu/Dataset/raw/refs/heads/main/Maternal%20Health%20Risk%20Data%20Set.zip
  loacl_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion